apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc

spec: #DETAIL ABOUT REPLIACA
  replicas: 2 #CREATE TOTAL 3 REPLICA 
  selector:
    app: mynginx

  #above templete information about RC
  template:
  #BELOW templete information about POD
 
    metadata:
      name: mynginx
      labels:
        app: mynginx
    spec:
      containers:
        - name: mynginx-container
          image: nginx
          ports:
            - containerPort: 80
