apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
  labels:
    app: mynginx

#Specification belongs to above labels app myapp 
spec:
  type: NodePort
  ports:
    - port: 80 
      nodePort: 30001
      protocol: TCP
  selector:
    app: mynginx

  #ports:
  #- port: <Port>
   # targetPort: <Target Port>

